(deftheme umberto
  "My programming theme. Work in progress.")

(custom-theme-set-faces
 'umberto
 '(default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeee" :background "#141414" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#F8F8F2" :foreground "#171A0B"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#75715E" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#66D9EF"))))
 '(highlight ((t (:background "#575757" :foreground "#ddd"))))
 '(region ((t (:background "#49483E"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#49483E"))))
 '(trailing-whitespace ((t (:background "#F92672"))))
 '(font-lock-builtin-face ((t (:foreground "Yellow"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face) :foreground "#676767"))))
 '(font-lock-comment-face ((t (:foreground "#676767"))))
 '(font-lock-constant-face ((t (:foreground "gray77"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face) :foreground "#75715E"))))
 '(font-lock-function-name-face ((t (:weight ultra-bold :foreground "dodger blue"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "chartreuse3"))))
 '(font-lock-negation-char-face ((t (:foreground "#75715E"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face) :foreground "gray77"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:foreground "dark cyan"))))
 '(font-lock-variable-name-face ((t (:foreground "gold"))))
 '(font-lock-warning-face ((t (:inherit (error) :foreground "#968B26" :weight bold))))
 '(button ((t (:inherit (link) :underline (:color foreground-color :style line)))))
 '(link ((t (:foreground "#66D9EF" :underline (:color foreground-color :style line) :weight bold))))
 '(link-visited ((t (:inherit (link) :foreground "#AE81FF" :underline (:color foreground-color :style line) :weight normal))))
 '(fringe ((t (:background "#272822" :foreground "#F8F8F2"))))
 '(header-line ((t (:inherit (mode-line) :background "#2B2B2B" :foreground "#F0DFAF" :box (:line-width -1 :color nil :style released-button)))))
 '(tooltip ((t (:inherit (variable-pitch) :background "lightyellow" :foreground "black"))))
 '(mode-line ((t (:background "#49483E" :foreground "#F8F8F2" :box (:line-width -1 :color nil :style released-button)))))
 '(mode-line-buffer-id ((t (:foreground "#A6E22E" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:inherit (mode-line) :background "#272822" :foreground "#49483E" :box (:line-width -1 :color nil :style released-button) :weight light))))
 '(isearch ((t (:background "#171A0B" :foreground "#FD971F" :weight bold))))
 '(isearch-fail ((t (:background "#F92672" :foreground "#F8F8F0"))))
 '(lazy-highlight ((t (:background "#171A0B" :foreground "#FD5FF0" :weight bold))))
 '(match ((t (:background "#171A0B" :foreground "#A6E22E" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'umberto)
